### ISSUE TITLE
无法增加相同的物品

### ISSUE THREAD

**Issue by xtz136** [Abab-bk/FlowerIventory#1]
使用环境：
godot：4.0
Flowerlventory：2.0-GD4

问题：
当没有 stack 字段的时候，无法增加相同的物品。例子：

```
inventory.add_item(1, 1, "weapons")
inventory.add_item(1, 1, "weapons")
```

结果：
背包里面应该有两个ID为1的武器，但是实际上只有一个。

最后如果有需要我可以提交代码，修复这个问题。

**Comment by Abab-bk** [comment]
666没想到真有人用这个插件😍
我今晚可以修一下，如果你修好了直接pr吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 中午12:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Abab-bk/FlowerIventory] 无法增加相同的物品 (Issue #1)




 
使用环境：
 godot：4.0
 Flowerlventory：2.0-GD4
 
问题：
 当没有 stack 字段的时候，无法增加相同的物品。例子：
 inventory.add_item(1, 1, "weapons") inventory.add_item(1, 1, "weapons")  
结果：
 背包里面应该有两个ID为1的武器，但是实际上只有一个。
 
最后如果有需要我可以提交代码，修复这个问题。

**Comment by xtz136** [comment]
我是新手，不知道怎么弄背包，才找到这个插件 ：），非常感谢你分享这个插件。

顺便说下，我一开始启用这个插件出错了，因为项目名称拼错了，和main.gd里面的写的路径不一致。

**Comment by Abab-bk** [comment]
谢谢你，因为我觉得没人用这个插件就没检查



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 下午2:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Hey R You ***@***.***&gt;;
主题: Re: [Abab-bk/FlowerIventory] 无法增加相同的物品 (Issue #1)




 
我是新手，不知道怎么弄背包，才找到这个插件 ：），非常感谢你分享这个插件。
 
顺便说下，我一开始启用这个插件出错了，因为项目名称拼错了，和main.gd里面的写的路径不一致。

**Comment by Abab-bk** [comment]
解决
